
spring:
  application:
    name: Spring_Video_Streaming

  data:
    redis:
      port: 19320
      host: redis-19320.c330.asia-south1-1.gce.redns.redis-cloud.com
      username: default
      password: v1VYzfJYqRUyHePpSswkuguwSPHCrgaB

  datasource:
    url: jdbc:mysql://67.217.240.192:3306/SpringBootVideo
    username: video_user
    password: 2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use 'create', 'create-drop', 'validate', or 'update' based on your requirements
    show-sql: true      # Enables SQL query logging in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Use the appropriate dialect for your MySQL version

  servlet:
    multipart:
      max-file-size: 20000MB
      max-request-size: 20000MB


video:
  directory: /var/videos


server:
  port: 9091

